version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      - 'POSTGRES_PASSWORD=jenkinsuplink'
      # Used for psql non-interactive scripting
      - 'PGPASSWORD=jenkinsuplink'
      - 'POSTGRES_DB=uplink_development'

  node:
    image: node:10
    command: '/usr/local/bin/node $PWD/node_modules/.bin/nodemon build'
    working_dir: $PWD
    environment:
      - 'PATH=$PWD/node_modules/.bin:$PATH'
      - 'NODE_ENV=$NODE_ENV'
      - 'DB_TRACING=true'
      - 'DEBUG=$DEBUG'
    volumes:
      - $PWD:$PWD
    ports:
      - '3030:3030'
    depends_on:
      - db
